### ISSUE TITLE
Getting `Protocol Version 1.0.0 is not supported.`.  Is my roku too old for this method?

### ISSUE THREAD

**Issue by jfrux** [rokucommunity/roku-debug#1]
Curious how to tell if my Roku does not support it or if I'm able to enable it somehow?

**Comment by chrisdp** [comment]
@jfrux wood question. So the protocol version is something the Roku send us. We didn’t start working on supporting this new protocol until they came out with step support in version 2. 

I don’t think there is any way to see the version on device right now but what I can say is version 2 is part of the Roku OS 9.3 update. They are currently rolling out this update to devices. Once your device is on 9.3 this error should go away.

**Comment by jfrux** [comment]
@chrisdp Ahh! So I'm not crazy.
The device i was using was a Roku 3.
Just plugged in a Roku Premier to see how that does since it's a bit better.

**Comment by chrisdp** [comment]
No problem. If you run into any issues or hangs please feel free to open issues so we can address them and thanks for trying it out!
