### ISSUE TITLE
Restart of debugger fails to connect to device

### ISSUE THREAD

**Issue by jimallison53** [rokucommunity/roku-debug#160]
Restart of the debugger consistently fails to connect to the device.  A **stop** followed by a **start** consistently succeeds to connect to the device.

**Restart** results in the following message in the Scenegraph Inspector window:

> **Failed to connect to Roku at 192.168.1.4 on port 9000. Make sure you have the on device component running on your Roku.**

**Comment by TwitchBronBron** [comment]
You mean clicking the "restart" (green circle arrow button in the debug
bar)? If so, then yeah, this is a known issue. There are some weird timing
issues in vscode that we haven't been able to fix yet.

**Comment by jimallison53** [comment]
"Restart Debugging" from the Debug menu as well, i.e. - "restart the debugger, period. I checked the Issues list before creating this issue - I didn't see anything describing this behavior.
