### ISSUE TITLE
Arrays not handled correctly when inspecting

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/roku-debug#3]
When inspecting arrays and using the socket debugger you are returned a recursive array of the item your trying to inspect.

**Comment by chrisdp** [comment]
I should have time to look at this issue early next week @TwitchBronBron so don’t worry about jumping on this. This issue only affects the debug protocol.

**Comment by TwitchBronBron** [comment]
@chrisdp this was resolved by #8 right?

**Comment by chrisdp** [comment]
Yes. Closing.
