### ISSUE TITLE
Add variable ignoring

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/roku-debug#68]
Our telnet adapter currently creates variables like `vscodeLoopKey`, `vscodeLoopItem`, etc. When we add execute support for watch panel in the debug protocol, we will also need to add other variables. So, we should do the following:

- establish an identifiable prefix (perhaps `__rokuDebug_`) that all our variables will start with
- remove these variables from all user-facing responses
- add a launch config option to disable the hiding, to support the rare case where someone else would want to use their own variables (or for our own debugging purposes).

**Comment by chrisdp** [comment]
Relates to #59
